// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcXBgDSmSu53hK-9wv801J-SukYLEPeQ',
    appId: '1:1074509389785:web:9efbee086f41d48a2943c8',
    messagingSenderId: '1074509389785',
    projectId: 'school-manager-6cb94',
    authDomain: 'school-manager-6cb94.firebaseapp.com',
    storageBucket: 'school-manager-6cb94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdfnQbxoFUnKpENT8bnVmmhDJOAWF5LW4',
    appId: '1:1074509389785:android:5c42fb44c40936c02943c8',
    messagingSenderId: '1074509389785',
    projectId: 'school-manager-6cb94',
    storageBucket: 'school-manager-6cb94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaVHqqkMYb3ps76xG_wQNnxizPfV23KA8',
    appId: '1:1074509389785:ios:1605c9a244d5f0a32943c8',
    messagingSenderId: '1074509389785',
    projectId: 'school-manager-6cb94',
    storageBucket: 'school-manager-6cb94.appspot.com',
    iosBundleId: 'com.example.schoolManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaVHqqkMYb3ps76xG_wQNnxizPfV23KA8',
    appId: '1:1074509389785:ios:1605c9a244d5f0a32943c8',
    messagingSenderId: '1074509389785',
    projectId: 'school-manager-6cb94',
    storageBucket: 'school-manager-6cb94.appspot.com',
    iosBundleId: 'com.example.schoolManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkcXBgDSmSu53hK-9wv801J-SukYLEPeQ',
    appId: '1:1074509389785:web:119558d63bc74ec42943c8',
    messagingSenderId: '1074509389785',
    projectId: 'school-manager-6cb94',
    authDomain: 'school-manager-6cb94.firebaseapp.com',
    storageBucket: 'school-manager-6cb94.appspot.com',
  );
}
